language: node_js
node_js:
  - "node"
before_script:
  - 'if [ -n "${KARMA-}" ]; then export DISPLAY=:99.0; fi'
  - 'if [ -n "${KARMA-}" ]; then sh -e /etc/init.d/xvfb start; fi'
  - 'if [ -n "${KARMA-}" ]; then sleep 3; fi'
  - 'if [ -n "${REACT-}" ] && [ "${TEST-}" = true ]; then sh install-relevant-react.sh && npm ls >/dev/null || echo "temporary bypass"; fi'
script:
  - 'if [ -n "${LINT-}" ]; then npm run lint ; fi'
  - 'if [ "${TEST-}" = true ]; then npm run tests-only ; fi'
  - 'if [ -n "${KARMA-}" ]; then npm run tests-karma ; fi'
  - 'if [ -n "${COVERAGE-}" ] && [ "${TRAVIS_BRANCH-}" = "master" ]; then npm run cover; cat ./coverage/lcov.info | ./node_modules/.bin/coveralls ; fi'
env:
  global:
    - REACT=15 TEST=true

deploy:
  - provider: npm
    email: v7rulnik@gmail.com
    skip_cleanup: true
    api_key: $NPM_TOKEN
    on:
      branch: master
      tags: true
      repo: kupibilet-frontend/react-dates
